### ISSUE TITLE
Request: a production-like demo for using this library

### ISSUE THREAD

**Issue by ttimasdf** [StringCare/stringcare#1]
I'm still confused after reading the wiki and the codes. From my understanding, this project implements a simple algorithm without any constants (like S-Box for AES) to defend against yara rules detection. However, there seems no code generation parts that makes the string list hard to maintain. Should I run something to manually generate the obfuscated strings (maybe byte array) and add them to my source code? Or is there a better way? Hoping there could be a better example of using this plugin.

Thanks for this great project after all!

**Comment by efraespada** [comment]
This project only makes it easier to work with data (obfuscating or revealing it) with C++ code, which difficult the reverse engineer process.

The unique scenario is at **runtime**:
- The application manages some data (ex. profile information (String), an image (Uint8List), or video (Uint8List)..).
- The data is obfuscated before store it locally.
- The data only can be revealed by the application.

> However, there seems no code generation parts that makes the string list hard to maintain. Should I run something to manually generate the obfuscated strings (maybe byte array) and add them to my source code? Or is there a better way?

For now, the resource obfuscation (like the [original Android library](https://github.com/StringCare/AndroidLibrary/wiki/What-is-StringCare)) is not included at **compilation time** but **it is a future improvement**.

As a production demo, you can check out [Land-a](https://landa-app.com/), an app I published that stores safely any text or media message you send/receive.

**Comment by efraespada** [comment]
@ttimasdf I've updated the repository.

> Should I run something to manually generate the obfuscated strings (maybe byte array) and add them to my source code?

I've added a command for obfuscating assets and localization files:

```bash
flutter pub run stringcare:obfuscate 
```

[i18n](https://github.com/StringCare/stringcare/wiki/i18n)

[Assets](https://github.com/StringCare/stringcare/wiki/Assets)
